# -*- coding: utf-8 -*-
"""Plant Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5WIOg4PcPpiMYcYTGleTjDN0PXZl2-n

use GPU for faster runtime
"""

import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

"""Install/import our project libraries"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import VGG16

print("OpenCV version:", cv2.__version__)
print("NumPy version:", np.__version__)
print("TensorFlow version:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

!pip install -q kagglehub

import kagglehub

path = kagglehub.dataset_download(
    "timothylovett/plantvillage-splits"
)

print("Dataset downloaded to:")
print(path)

import os

dataset_path = path

print("Dataset path:")
print(dataset_path)

print("\nTop-level contents:")
for item in os.listdir(dataset_path):
    print("-", item)

train_path = os.path.join(dataset_path, "train")

classes = sorted([
    folder for folder in os.listdir(train_path)
    if os.path.isdir(os.path.join(train_path, folder))
])

print("Number of classes:", len(classes))

print("\nClasses:")
for i, class_name in enumerate(classes):
    print(f"{i}: {class_name}")

import os

splits = ["train", "valid", "test"]

for split in splits:
    split_path = os.path.join(dataset_path, split)

    print(f"\n{'=' * 60}")
    print(f"{split.upper()}")
    print(f"{'=' * 60}")

    total_images = 0

    for class_name in sorted(os.listdir(split_path)):
        class_path = os.path.join(split_path, class_name)

        if os.path.isdir(class_path):
            image_count = len([
                f for f in os.listdir(class_path)
                if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
            ])

            total_images += image_count
            print(f"{class_name}: {image_count}")

    print(f"\nTotal {split} images: {total_images}")

"""dataset summary"""

import os
import pandas as pd

splits = ["train", "valid", "test"]

class_counts = {}

for split in splits:
    split_path = os.path.join(dataset_path, split)
    class_counts[split] = {}

    for class_name in sorted(os.listdir(split_path)):
        class_path = os.path.join(split_path, class_name)

        if os.path.isdir(class_path):
            image_count = len([
                f for f in os.listdir(class_path)
                if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
            ])

            class_counts[split][class_name] = image_count


classes = sorted(class_counts["train"].keys())

summary = pd.DataFrame({
    "Class": classes,
    "Train": [class_counts["train"].get(c, 0) for c in classes],
    "Validation": [class_counts["valid"].get(c, 0) for c in classes],
    "Test": [class_counts["test"].get(c, 0) for c in classes]
})

summary["Total"] = (
    summary["Train"] +
    summary["Validation"] +
    summary["Test"]
)

print("Number of classes:", len(summary))
print("Total images:", summary["Total"].sum())

summary

import os
import cv2
import random

# Select a few classes to inspect
sample_classes = [
    "Apple___Apple_scab",
    "Apple___healthy",
    "Corn_(maize)___Common_rust_",
    "Potato___Late_blight",
    "Tomato___healthy"
]

for class_name in sample_classes:
    class_path = os.path.join(dataset_path, "train", class_name)

    images = [
        f for f in os.listdir(class_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
    ]

    image_file = random.choice(images)
    image_path = os.path.join(class_path, image_file)

    image = cv2.imread(image_path)

    print(f"\nClass: {class_name}")
    print("File:", image_file)
    print("Shape:", image.shape)
    print("Data type:", image.dtype)

import os
import cv2
import random
import matplotlib.pyplot as plt

sample_classes = [
    "Apple___Apple_scab",
    "Apple___healthy",
    "Corn_(maize)___Common_rust_",
    "Potato___Late_blight",
    "Tomato___healthy"
]

fig, axes = plt.subplots(1, 5, figsize=(20, 4))

for ax, class_name in zip(axes, sample_classes):

    class_path = os.path.join(dataset_path, "train", class_name)

    images = [
        f for f in os.listdir(class_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
    ]

    image_file = random.choice(images)
    image_path = os.path.join(class_path, image_file)

    # OpenCV reads BGR
    image = cv2.imread(image_path)

    # Convert BGR → RGB for Matplotlib
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    ax.imshow(image_rgb)
    ax.set_title(class_name, fontsize=9)
    ax.axis("off")

plt.tight_layout()
plt.show()

# Class imbalance analysis

min_class = summary.loc[summary["Train"].idxmin()]
max_class = summary.loc[summary["Train"].idxmax()]

print("Smallest training class:")
print(f"  {min_class['Class']}: {min_class['Train']} images")

print("\nLargest training class:")
print(f"  {max_class['Class']}: {max_class['Train']} images")

imbalance_ratio = max_class["Train"] / min_class["Train"]

print(f"\nImbalance ratio: {imbalance_ratio:.2f}:1")

print(f"\nMean training images/class: {summary['Train'].mean():.2f}")
print(f"Median training images/class: {summary['Train'].median():.2f}")

from tensorflow.keras.applications.vgg16 import preprocess_input

# Pick one image
class_name = "Apple___Apple_scab"

class_path = os.path.join(
    dataset_path,
    "train",
    class_name
)

image_files = [
    f for f in os.listdir(class_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
]

image_path = os.path.join(class_path, image_files[0])

# Read image using OpenCV
image = cv2.imread(image_path)

print("Original shape:", image.shape)
print("Original dtype:", image.dtype)
print("Original min:", image.min())
print("Original max:", image.max())

# BGR → RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Add batch dimension
image_batch = np.expand_dims(image_rgb, axis=0)

# VGG16 preprocessing
processed_image = preprocess_input(image_batch.copy())

print("\nAfter VGG16 preprocessing:")
print("Shape:", processed_image.shape)
print("Dtype:", processed_image.dtype)
print("Min:", processed_image.min())
print("Max:", processed_image.max())

"""Create the datasets"""

from tensorflow.keras.applications.vgg16 import preprocess_input

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

train_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(dataset_path, "train"),
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=SEED
)

valid_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(dataset_path, "valid"),
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(dataset_path, "test"),
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names

print("\nNumber of classes:", len(class_names))
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(AUTOTUNE)
valid_ds = valid_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

print("Dataset pipelines optimized with prefetching.")

"""Build the baseline VGG16 model"""

from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras import layers, models

NUM_CLASSES = len(class_names)

# Load pretrained VGG16
base_model = VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze the entire VGG16 base
base_model.trainable = False

# Build the classification model
model_m1 = models.Sequential([
    layers.Input(shape=(224, 224, 3)),

    # VGG16 preprocessing
    layers.Lambda(preprocess_input),

    # Pretrained VGG16
    base_model,

    # Classification head
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation="softmax")
])

model_m1.summary()

model_m1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("M1 compiled successfully.")

"""Set up training callbacks"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

m1_checkpoint_path = "/content/plantvillage_m1_baseline.keras"

m1_callbacks = [
    ModelCheckpoint(
        m1_checkpoint_path,
        monitor="val_loss",
        save_best_only=True,
        mode="min",
        verbose=1
    ),

    EarlyStopping(
        monitor="val_loss",
        patience=3,
        mode="min",
        restore_best_weights=True,
        verbose=1
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.2,
        patience=2,
        mode="min",
        min_lr=1e-6,
        verbose=1
    )
]

print("M1 callbacks configured.")
print("Checkpoint:", m1_checkpoint_path)

"""Train M1"""

m1_history = model_m1.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=10,
    callbacks=m1_callbacks
)

"""Plot M1 training curves"""

import matplotlib.pyplot as plt

history = m1_history.history

plt.figure(figsize=(8, 5))
plt.plot(history["accuracy"], label="Training Accuracy")
plt.plot(history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("M1 — Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history["loss"], label="Training Loss")
plt.plot(history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("M1 — Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# Evaluate M1 on the untouched test set

test_loss, test_accuracy = model_m1.evaluate(test_ds, verbose=1)

print("\nM1 Test Results")
print("=" * 40)
print(f"Test Loss:     {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4%}")

"""M1 classification report"""

from sklearn.metrics import classification_report
import numpy as np

# Get true labels and predictions
y_true = []
y_pred = []

for images, labels in test_ds:
    predictions = model_m1.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(predictions, axis=1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Classification report
report = classification_report(
    y_true,
    y_pred,
    target_names=class_names,
    digits=4
)

print(report)

"""M1 Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(18, 16))

plt.imshow(cm, interpolation="nearest")
plt.title("M1 — PlantVillage Confusion Matrix")
plt.colorbar()

plt.xticks(
    np.arange(len(class_names)),
    class_names,
    rotation=90,
    fontsize=8
)

plt.yticks(
    np.arange(len(class_names)),
    class_names,
    fontsize=8
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")

plt.tight_layout()
plt.show()

"""M1 confusions"""

# Find the largest confusion pairs

confusions = []

for true_idx in range(len(class_names)):
    for pred_idx in range(len(class_names)):
        if true_idx != pred_idx and cm[true_idx, pred_idx] > 0:
            confusions.append({
                "True Class": class_names[true_idx],
                "Predicted As": class_names[pred_idx],
                "Count": cm[true_idx, pred_idx]
            })

confusions = sorted(
    confusions,
    key=lambda x: x["Count"],
    reverse=True
)

print("Top 15 M1 confusion pairs:")
print("=" * 80)

for item in confusions[:15]:
    print(
        f"{item['True Class']} "
        f"→ {item['Predicted As']} "
        f": {item['Count']} images"
    )

import os

model_path = "/content/plantvillage_m1_baseline.keras"

print("Model exists:", os.path.exists(model_path))

if os.path.exists(model_path):
    print("Model size:", os.path.getsize(model_path) / (1024 * 1024), "MB")

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Upload an image
uploaded = files.upload()

image_name = next(iter(uploaded))

# Read image
image = cv2.imread(image_name)

if image is None:
    raise ValueError("Could not read the uploaded image.")

# OpenCV BGR → RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Resize to VGG16 input size
image_resized = cv2.resize(image_rgb, (224, 224))

# Add batch dimension
image_batch = np.expand_dims(
    image_resized.astype(np.float32),
    axis=0
)

# IMPORTANT:
# model_m1 already contains VGG16 preprocess_input.
predictions = model_m1.predict(image_batch, verbose=0)[0]

# Top 3 predictions
top_indices = np.argsort(predictions)[::-1][:3]

print("\n" + "=" * 55)
print("       PLANT DISEASE CLASSIFICATION")
print("=" * 55)

for rank, index in enumerate(top_indices, start=1):
    print(
        f"{rank}. {class_names[index]}"
        f" — {predictions[index] * 100:.2f}%"
    )

print("=" * 55)

# Display image
plt.figure(figsize=(6, 6))
plt.imshow(image_rgb)
plt.title(
    f"Prediction: {class_names[top_indices[0]]}\n"
    f"Confidence: {predictions[top_indices[0]] * 100:.2f}%"
)
plt.axis("off")
plt.show()

model_m1.save("/content/plantvillage_m1_baseline.keras")

print("Model saved successfully.")

import os

model_path = "/content/plantvillage_m1_baseline.keras"

print("Exists:", os.path.exists(model_path))
print("Size:", os.path.getsize(model_path) / (1024**2), "MB")

import zipfile

model_path = "/content/plantvillage_m1_baseline.keras"

with zipfile.ZipFile(model_path, "r") as z:
    bad_file = z.testzip()

print("Corruption check:", bad_file)

from google.colab import files

files.download("/content/plantvillage_m1_baseline.keras")